// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Screen_MoonPhase_screen_init(void)
{
ui_Screen_MoonPhase = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen_MoonPhase, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Screen_MoonPhase, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Screen_MoonPhase, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label_Time = lv_label_create(ui_Screen_MoonPhase);
lv_obj_set_width( ui_Label_Time, LV_SIZE_CONTENT);  /// 162
lv_obj_set_height( ui_Label_Time, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label_Time, 2 );
lv_obj_set_y( ui_Label_Time, 72 );
lv_obj_set_align( ui_Label_Time, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label_Time,"00:00");
lv_obj_set_style_text_color(ui_Label_Time, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label_Time, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_Time, &ui_font_IBM70, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel_Abbr2 = lv_obj_create(ui_Screen_MoonPhase);
lv_obj_set_width( ui_Panel_Abbr2, 55);
lv_obj_set_height( ui_Panel_Abbr2, 36);
lv_obj_set_x( ui_Panel_Abbr2, 86 );
lv_obj_set_y( ui_Panel_Abbr2, 58 );
lv_obj_set_align( ui_Panel_Abbr2, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel_Abbr2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Panel_Abbr2, 15, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Panel_Abbr2, lv_color_hex(0xB6B5B6), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel_Abbr2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Panel_Abbr2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Panel_Abbr2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Panel_Abbr2, 5, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label_Abbr2 = lv_label_create(ui_Panel_Abbr2);
lv_obj_set_width( ui_Label_Abbr2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label_Abbr2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label_Abbr2, 0 );
lv_obj_set_y( ui_Label_Abbr2, -1 );
lv_obj_set_align( ui_Label_Abbr2, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label_Abbr2,"AM");
lv_obj_set_style_text_color(ui_Label_Abbr2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label_Abbr2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_Abbr2, &ui_font_IBM25, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label_Date = lv_label_create(ui_Screen_MoonPhase);
lv_obj_set_width( ui_Label_Date, LV_SIZE_CONTENT);  /// 162
lv_obj_set_height( ui_Label_Date, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label_Date, 84 );
lv_obj_set_y( ui_Label_Date, -68 );
lv_obj_set_align( ui_Label_Date, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label_Date,"14");
lv_obj_set_style_text_color(ui_Label_Date, lv_color_hex(0xB6B5B6), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label_Date, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_Date, &ui_font_IBM45, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label_Month = lv_label_create(ui_Screen_MoonPhase);
lv_obj_set_width( ui_Label_Month, LV_SIZE_CONTENT);  /// 162
lv_obj_set_height( ui_Label_Month, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label_Month, 84 );
lv_obj_set_y( ui_Label_Month, -100 );
lv_obj_set_align( ui_Label_Month, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label_Month,"APR");
lv_obj_set_style_text_color(ui_Label_Month, lv_color_hex(0xB6B5B6), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label_Month, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_Month, &ui_font_IBM25, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label_Day = lv_label_create(ui_Screen_MoonPhase);
lv_obj_set_width( ui_Label_Day, LV_SIZE_CONTENT);  /// 162
lv_obj_set_height( ui_Label_Day, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label_Day, 86 );
lv_obj_set_y( ui_Label_Day, -36 );
lv_obj_set_align( ui_Label_Day, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label_Day,"MON");
lv_obj_set_style_text_color(ui_Label_Day, lv_color_hex(0xB6B5B6), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label_Day, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_Day, &ui_font_IBM25, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image_Moon = lv_img_create(ui_Screen_MoonPhase);
lv_img_set_src(ui_Image_Moon, &ui_img_moon_phase_moon_frame_00003_png);
lv_obj_set_width( ui_Image_Moon, LV_SIZE_CONTENT);  /// 170
lv_obj_set_height( ui_Image_Moon, LV_SIZE_CONTENT);   /// 170
lv_obj_set_x( ui_Image_Moon, 0 );
lv_obj_set_y( ui_Image_Moon, -14 );
lv_obj_set_align( ui_Image_Moon, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image_Moon, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image_Moon, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label_Phase = lv_label_create(ui_Screen_MoonPhase);
lv_obj_set_width( ui_Label_Phase, 162);
lv_obj_set_height( ui_Label_Phase, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label_Phase, -29 );
lv_obj_set_y( ui_Label_Phase, -82 );
lv_obj_set_align( ui_Label_Phase, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label_Phase,"Waxing Crescent");
lv_obj_set_style_text_color(ui_Label_Phase, lv_color_hex(0xB6B5B6), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label_Phase, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Label_Phase, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_Phase, &ui_font_IBM25, LV_PART_MAIN| LV_STATE_DEFAULT);

}
