// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

void Moon_Animation( lv_obj_t *TargetObject, int delay);

// SCREEN: ui_Screen_Time
void ui_Screen_Time_screen_init(void);
extern lv_obj_t *ui_Screen_Time;
extern lv_obj_t *ui_Label_HH;
extern lv_obj_t *ui_Label_Colon;
extern lv_obj_t *ui_Label_MM;
extern lv_obj_t *ui_Panel_Abbr;
extern lv_obj_t *ui_Label_Abbr;
// CUSTOM VARIABLES

// SCREEN: ui_Screen_MoonPhase
void ui_Screen_MoonPhase_screen_init(void);
extern lv_obj_t *ui_Screen_MoonPhase;
extern lv_obj_t *ui_Label_Time;
extern lv_obj_t *ui_Panel_Abbr2;
extern lv_obj_t *ui_Label_Abbr2;
extern lv_obj_t *ui_Label_Date;
extern lv_obj_t *ui_Label_Month;
extern lv_obj_t *ui_Label_Day;
extern lv_obj_t *ui_Image_Moon;
extern lv_obj_t *ui_Label_Phase;
// CUSTOM VARIABLES

// EVENTS
extern lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE( ui_img_moon_phase_moon_frame_00003_png);   // assets/Moon_Phase/Moon_Frame_00003.png
LV_IMG_DECLARE( ui_img_moon_phase_moon_frame_00000_png);   // assets/Moon_Phase/Moon_Frame_00000.png
LV_IMG_DECLARE( ui_img_moon_phase_moon_frame_00001_png);   // assets/Moon_Phase/Moon_Frame_00001.png
LV_IMG_DECLARE( ui_img_moon_phase_moon_frame_00002_png);   // assets/Moon_Phase/Moon_Frame_00002.png
LV_IMG_DECLARE( ui_img_moon_phase_moon_frame_00004_png);   // assets/Moon_Phase/Moon_Frame_00004.png
LV_IMG_DECLARE( ui_img_moon_phase_moon_frame_00005_png);   // assets/Moon_Phase/Moon_Frame_00005.png
LV_IMG_DECLARE( ui_img_moon_phase_moon_frame_00006_png);   // assets/Moon_Phase/Moon_Frame_00006.png
LV_IMG_DECLARE( ui_img_moon_phase_moon_frame_00007_png);   // assets/Moon_Phase/Moon_Frame_00007.png
LV_IMG_DECLARE( ui_img_moon_phase_moon_frame_00008_png);   // assets/Moon_Phase/Moon_Frame_00008.png
LV_IMG_DECLARE( ui_img_moon_phase_moon_frame_00009_png);   // assets/Moon_Phase/Moon_Frame_00009.png
LV_IMG_DECLARE( ui_img_moon_phase_moon_frame_00010_png);   // assets/Moon_Phase/Moon_Frame_00010.png
LV_IMG_DECLARE( ui_img_moon_phase_moon_frame_00011_png);   // assets/Moon_Phase/Moon_Frame_00011.png
LV_IMG_DECLARE( ui_img_moon_phase_moon_frame_00012_png);   // assets/Moon_Phase/Moon_Frame_00012.png
LV_IMG_DECLARE( ui_img_moon_phase_moon_frame_00013_png);   // assets/Moon_Phase/Moon_Frame_00013.png
LV_IMG_DECLARE( ui_img_moon_phase_moon_frame_00014_png);   // assets/Moon_Phase/Moon_Frame_00014.png
LV_IMG_DECLARE( ui_img_moon_phase_moon_frame_00015_png);   // assets/Moon_Phase/Moon_Frame_00015.png
LV_IMG_DECLARE( ui_img_moon_phase_moon_frame_00016_png);   // assets/Moon_Phase/Moon_Frame_00016.png
LV_IMG_DECLARE( ui_img_moon_phase_moon_frame_00017_png);   // assets/Moon_Phase/Moon_Frame_00017.png
LV_IMG_DECLARE( ui_img_moon_phase_moon_frame_00018_png);   // assets/Moon_Phase/Moon_Frame_00018.png
LV_IMG_DECLARE( ui_img_moon_phase_moon_frame_00019_png);   // assets/Moon_Phase/Moon_Frame_00019.png
LV_IMG_DECLARE( ui_img_moon_phase_moon_frame_00020_png);   // assets/Moon_Phase/Moon_Frame_00020.png
LV_IMG_DECLARE( ui_img_moon_phase_moon_frame_00021_png);   // assets/Moon_Phase/Moon_Frame_00021.png
LV_IMG_DECLARE( ui_img_moon_phase_moon_frame_00022_png);   // assets/Moon_Phase/Moon_Frame_00022.png
LV_IMG_DECLARE( ui_img_moon_phase_moon_frame_00023_png);   // assets/Moon_Phase/Moon_Frame_00023.png
LV_IMG_DECLARE( ui_img_moon_phase_moon_frame_00024_png);   // assets/Moon_Phase/Moon_Frame_00024.png
LV_IMG_DECLARE( ui_img_moon_phase_moon_frame_00025_png);   // assets/Moon_Phase/Moon_Frame_00025.png
LV_IMG_DECLARE( ui_img_moon_phase_moon_frame_00026_png);   // assets/Moon_Phase/Moon_Frame_00026.png
LV_IMG_DECLARE( ui_img_moon_phase_moon_frame_00027_png);   // assets/Moon_Phase/Moon_Frame_00027.png
LV_IMG_DECLARE( ui_img_moon_phase_moon_frame_00028_png);   // assets/Moon_Phase/Moon_Frame_00028.png
LV_IMG_DECLARE( ui_img_moon_phase_moon_frame_00029_png);   // assets/Moon_Phase/Moon_Frame_00029.png

// FONTS
LV_FONT_DECLARE( ui_font_IBM110);
LV_FONT_DECLARE( ui_font_IBM170);
LV_FONT_DECLARE( ui_font_IBM25);
LV_FONT_DECLARE( ui_font_IBM45);
LV_FONT_DECLARE( ui_font_IBM70);

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
